### ISSUE TITLE
i got this error while using this extension for a month "Error: You exceeded your current quota, please check your plan and billing details." , i am waiting for fixing from provider but not yet

### ISSUE THREAD

**Issue by thanhcongchien** [rubberduck-ai/rubberduck-vscode#91] opened 2023-04-19 02:25 UTC
## Describe the bug

I got this error while using this extension for a month "Error: You exceeded your current quota, please check your plan and billing details." , i am waiting for fixing from provider but not yet

## How to reproduce

I have just used for a month and got this issue

## Expected behavior

I found many answers from various sources, and most of the best advice is to wait for the vendor to fix it.
I hope you can fix it as soon as possible.

## Screenshots
![alt](https://i.imgur.com/2EolpiI.png)

## Additional information

- Version of the extension impacted: _v1.15.0

_🧙‍ Add any other context about the problem here._

**Comment by lgrammel** [comment] 2023-04-19 06:44
Duplicate of issue #67 - Rubberduck uses your OpenAI credits. When you have used up your credits, it won't work.

**Closed by lgrammel** 2023-04-19 06:44 UTC
Labels: bug

**Comment by thanhcongchien** [comment] 2023-04-21 01:25
According to my research, there are many people who have paid but still receive such messages and they say it is a bug in the system and should wait to be fixed.
